var thehtml = `<div style = "width=device-width; initial-scale=1; maximum-scale=1; user-scalable=no">
<h3>Recent Updates (Online)</h3>
Tonight is the final night of "TRAP", the Autumn play at OHS. Come find out what the secret is at this final performance. Tickets are on sale online until 7:30 PM. Doors open at 7 PM and the perfromace starts at 7:30 PM.<br>
<a style="
align-content: normal;
align-items: normal;
align-self: auto;
animation-delay: 0s;
animation-direction: normal;
animation-duration: 0s;
animation-fill-mode: none;
animation-iteration-count: 1;
animation-name: none;
animation-play-state: running;
animation-timing-function: ease;
backface-visibility: visible;
background-attachment: scroll;
background-blend-mode: normal;
background-clip: border-box;
background-color: rgb(57, 107, 158);
background-image: linear-gradient(rgb(95, 156, 197), rgb(57, 107, 158));
background-origin: padding-box;
background-position: 0% 0%;
background-position-x: 0%;
background-position-y: 0%;
background-repeat: repeat;
background-size: auto;
block-size: 37.2px;
border-block-end-color: rgb(4, 64, 98);
border-block-end-style: solid;
border-block-end-width: 0px;
border-block-start-color: rgb(4, 64, 98);
border-block-start-style: solid;
border-block-start-width: 1px;
border-bottom-color: rgb(4, 64, 98);
border-bottom-left-radius: 0px;
border-bottom-right-radius: 0px;
border-bottom-style: solid;
border-bottom-width: 0px;
border-collapse: separate;
border-end-end-radius: 0px;
border-end-start-radius: 0px;
border-image-outset: 0;
border-image-repeat: stretch;
border-image-slice: 100%;
border-image-source: none;
border-image-width: 1;
border-inline-end-color: rgb(4, 64, 98);
border-inline-end-style: solid;
border-inline-end-width: 1px;
border-inline-start-color: rgb(4, 64, 98);
border-inline-start-style: solid;
border-inline-start-width: 1px;
border-left-color: rgb(4, 64, 98);
border-left-style: solid;
border-left-width: 1px;
border-right-color: rgb(4, 64, 98);
border-right-style: solid;
border-right-width: 1px;
border-spacing: 0px 0px;
border-start-end-radius: 0px;
border-start-start-radius: 0px;
border-top-color: rgb(4, 64, 98);
border-top-left-radius: 0px;
border-top-right-radius: 0px;
border-top-style: solid;
border-top-width: 1px;
bottom: 0px;
box-decoration-break: slice;
box-shadow: none;
box-sizing: content-box;
break-after: auto;
break-before: auto;
break-inside: auto;
caption-side: top;
caret-color: rgb(255, 255, 255);
clear: none;
clip: auto;
clip-path: none;
clip-rule: nonzero;
color: rgb(255, 255, 255);
color-adjust: economy;
color-interpolation: srgb;
color-interpolation-filters: linearrgb;
column-count: auto;
column-fill: balance;
column-gap: normal;
column-rule-color: rgb(255, 255, 255);
column-rule-style: none;
column-rule-width: 0px;
column-width: auto;
content: none;
counter-increment: none;
counter-reset: none;
cursor: pointer;
direction: ltr;
display: block;
dominant-baseline: auto;
empty-cells: show;
fill: rgb(0, 0, 0);
fill-opacity: 1;
fill-rule: nonzero;
filter: none;
flex-basis: auto;
flex-direction: row;
flex-grow: 0;
flex-shrink: 1;
flex-wrap: nowrap;
float: none;
flood-color: rgb(0, 0, 0);
flood-opacity: 1;
font-family: Helvetica, Arial, sans-serif;
font-feature-settings: normal;
font-kerning: auto;
font-language-override: normal;
font-size: 16px;
font-size-adjust: none;
font-stretch: 100%;
font-style: normal;
font-synthesis: weight style;
font-variant: normal;
font-variant-alternates: normal;
font-variant-caps: normal;
font-variant-east-asian: normal;
font-variant-ligatures: normal;
font-variant-numeric: normal;
font-variant-position: normal;
font-weight: 700;
grid-auto-columns: auto;
grid-auto-flow: row;
grid-auto-rows: auto;
grid-column-end: auto;
grid-column-start: auto;
grid-row-end: auto;
grid-row-start: auto;
grid-template-areas: none;
grid-template-columns: none;
grid-template-rows: none;
height: 37.2px;
hyphens: manual;
image-orientation: none;
image-rendering: auto;
ime-mode: auto;
inline-size: 1578px;
inset-block-end: 0px;
inset-block-start: 0px;
inset-inline-end: 0px;
inset-inline-start: 0px;
isolation: auto;
justify-content: normal;
justify-items: normal;
justify-self: auto;
left: 0px;
letter-spacing: normal;
lighting-color: rgb(255, 255, 255);
line-height: 17px;
list-style-image: none;
list-style-position: outside;
list-style-type: disc;
margin-block-end: 0px;
margin-block-start: 0px;
margin-bottom: 0px;
margin-inline-end: 0px;
margin-inline-start: 0px;
margin-left: 0px;
margin-right: 0px;
margin-top: 0px;
marker-end: none;
marker-mid: none;
marker-start: none;
mask: none;
mask-clip: border-box;
mask-composite: add;
mask-image: none;
mask-mode: match-source;
mask-origin: border-box;
mask-position: 0% 0%;
mask-position-x: 0%;
mask-position-y: 0%;
mask-repeat: repeat;
mask-size: auto;
mask-type: luminance;
max-block-size: none;
max-height: none;
max-inline-size: none;
max-width: none;
min-block-size: 0px;
min-height: 0px;
min-inline-size: 0px;
min-width: 0px;
mix-blend-mode: normal;
object-fit: fill;
object-position: 50% 50%;
opacity: 1;
order: 0;
outline-color: rgb(255, 255, 255);
outline-offset: 0px;
outline-style: none;
outline-width: 0px;
overflow: visible;
overflow-anchor: auto;
overflow-wrap: normal;
overflow-x: visible;
overflow-y: visible;
overscroll-behavior-x: auto;
overscroll-behavior-y: auto;
padding-block-end: 0px;
padding-block-start: 0px;
padding-bottom: 0px;
padding-inline-end: 0px;
padding-inline-start: 0px;
padding-left: 0px;
padding-right: 0px;
padding-top: 0px;
page-break-after: auto;
page-break-before: auto;
paint-order: normal;
perspective: none;
perspective-origin: 790px 19.1px;
pointer-events: auto;
position: relative;
quotes: "“" "”" "‘" "’";
resize: none;
right: 0px;
row-gap: normal;
ruby-align: space-around;
ruby-position: over;
scroll-behavior: auto;
scroll-snap-coordinate: none;
scroll-snap-destination: 0px 0px;
scroll-snap-points-x: none;
scroll-snap-points-y: none;
scroll-snap-type-x: none;
scroll-snap-type-y: none;
scrollbar-color: auto;
scrollbar-width: auto;
shape-image-threshold: 0;
shape-margin: 0px;
shape-outside: none;
shape-rendering: auto;
stop-color: rgb(0, 0, 0);
stop-opacity: 1;
stroke: none;
stroke-dasharray: none;
stroke-dashoffset: 0px;
stroke-linecap: butt;
stroke-linejoin: miter;
stroke-miterlimit: 4;
stroke-opacity: 1;
stroke-width: 1px;
table-layout: auto;
text-align: center;
text-align-last: auto;
text-anchor: start;
text-combine-upright: none;
text-decoration: none;
text-decoration-color: rgb(255, 255, 255);
text-decoration-line: none;
text-decoration-style: solid;
text-emphasis-color: rgb(255, 255, 255);
text-emphasis-position: over right;
text-emphasis-style: none;
text-indent: 0px;
text-justify: auto;
text-orientation: mixed;
text-overflow: clip;
text-rendering: auto;
text-shadow: rgb(25, 75, 126) 0px 1px 1px;
text-transform: none;
top: 0px;
touch-action: auto;
transform: none;
transform-box: border-box;
transform-origin: 790px 19.1px;
transform-style: flat;
transition-delay: 0s;
transition-duration: 0s;
transition-property: all;
transition-timing-function: ease;
unicode-bidi: normal;
vector-effect: none;
vertical-align: baseline;
visibility: visible;
white-space: normal;
width: 1578px;
will-change: auto;
word-break: normal;
word-spacing: 0px;
writing-mode: horizontal-tb;
z-index: auto;
-moz-appearance: none;
-moz-box-align: stretch;
-moz-box-direction: normal;
-moz-box-flex: 0;
-moz-box-ordinal-group: 1;
-moz-box-orient: horizontal;
-moz-box-pack: start;
-moz-float-edge: content-box;
-moz-force-broken-image-icon: 0;
-moz-image-region: auto;
-moz-orient: inline;
-moz-outline-radius-bottomleft: 0px;
-moz-outline-radius-bottomright: 0px;
-moz-outline-radius-topleft: 0px;
-moz-outline-radius-topright: 0px;
-moz-stack-sizing: stretch-to-fit;
-moz-tab-size: 8;
-moz-text-size-adjust: auto;
-moz-user-focus: none;
-moz-user-input: auto;
-moz-user-modify: read-only;
-moz-user-select: auto;
-moz-window-dragging: default;
-webkit-text-fill-color: rgb(255, 255, 255);
-webkit-text-stroke-color: rgb(255, 255, 255);
-webkit-text-stroke-width: 0px;
"
href="https://www.purplepass.com/#193941/Olympia_School_District_-_Theater_Productions-OHS_Theatre_Arts_Presents:_TRAP-Olympia_High_School-November-16-2019.html" data-theme="b" target="_blank" data-role="button"><span class="ui-btn-inner"
 style="
border-bottom-color: rgba(255, 255, 255, 0.3);
border-left-color: rgba(255, 255, 255, 0.3);
border-right-color: rgba(255, 255, 255, 0.3);
border-top-color: rgba(255, 255, 255, 0.3);
border-top-style: solid;
border-top-width: 1px;
color: rgb(255, 255, 255);
cursor: pointer;
display: block;
font-family: Helvetica, Arial, sans-serif;
font-size: 16px;
font-weight: 700;
min-width: 12px;
overflow: hidden;
overflow-x: hidden;
overflow-y: hidden;
padding-bottom: 9.6px;
padding-left: 20px;
padding-right: 20px;
padding-top: 9.6px;
position: relative;
text-align: center;
text-overflow: ellipsis;
text-shadow: rgb(25, 75, 126) 0px 1px 1px;
white-space: nowrap;
"><span class="ui-btn-text"
 style="
color: rgb(255, 255, 255);
cursor: pointer;
font-family: Helvetica, Arial, sans-serif;
font-size: 16px;
font-weight: 700;
position: relative;
text-align: center;
text-shadow: rgb(25, 75, 126) 0px 1px 1px;
white-space: nowrap;
width: 100%;
z-index: 1;
-moz-user-select: none;
">Buy or View Tickets</span></span></a></div>
`;

document.getElementById("thesub").innerHTML = thehtml;
 
